layout_spectrum: 0.19541788064367552
typography_spectrum: 0.9830052029702923
color:
  brandStrength: 0.5984202507911895
  lightness: 0.4774576600777483
  saturation: 0.6750566427912195
  rhythmicContrast: 0.31236503673385424
  brandColors:
    - '#D8CAA8'
    - '#5C832F'
    - '#284907'
    - '#382513'
    - '#363942'
coverPrefs:
  filter: false
github: true
analytics:
  google: UA-113319641-1
author:
  name: Mystic
  email: johnkelly.main@gmail.com
name: mysticstatistic
url: 'http://mysticstatistic.com'
navigation:
  - name: About Me
    id: 84a914e3-b9a2-44e2-88b8-19407ebe9cd7
    type: content
title: that mystic statistic...
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/2a7eef9e-4dd1-4d82-9d9d-3a9873bc9ff1.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/2a7eef9e-4dd1-4d82-9d9d-3a9873bc9ff1.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: some data dudes rambling
purpose:
  - type: contact
    url: 'mailto:johnkelly.main@gmail.com'
    label: Contact me
  - type: internal
    label: about me
    item: 84a914e3-b9a2-44e2-88b8-19407ebe9cd7
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6e1a9d7c-3d60-46a3-9591-7d16ff484903.png
