layout_spectrum: 0.6048671443854449
typography_spectrum: 0.29104242160289295
color:
  brandStrength: 0.0900758560853872
  lightness: 0.12002510019688692
  saturation: 0.6917423928706067
  rhythmicContrast: 0.09704765772115033
  brandColors:
    - '#10222B'
    - '#95AB63'
    - '#BDD684'
    - '#E2F0D6'
    - '#F6FFE0'
coverPrefs:
  filter: false
github: true
author:
  name: Mystic
  email: johnkelly.main@gmail.com
name: mysticstatistic
url: 'http://mysticstatistic.com'
title: that mystic statistic...
content: []
description: some data dudes rambling
purpose:
  - type: contact
    url: 'mailto:johnkelly.main@gmail.com'
    label: Email me
  - type: contact
    url: 'tel:07808014470'
    label: Call me
