typography_spectrum: 0.5989055317140525
color:
  brandStrength: 0.13748945845493882
  lightness: 0.3601281377937792
  saturation: 0.3945618999767864
  rhythmicContrast: 0.219388227790299
  brandColors:
    - '#004358'
    - '#1F8A70'
    - '#BEDB39'
    - '#FFE11A'
    - '#FD7400'
github: true
layout_spectrum: 0.0942682936585665
author:
  name: Mystic
  email: johnkelly.main@gmail.com
name: mysticstatistic
title: 'number, stats, and sexy times!'
content: []
description: (but there's no sexy times.)
purpose:
  - type: contact
    url: 'mailto:johnkelly.main@gmail.com'
    label: Contact me
  - type: contact
    url: 'tel:07808014470'
    label: Call 07808014470
