typography_spectrum: 0.9096295643090686
color:
  brandStrength: 0.8624461497755556
  lightness: 0.6355742091268743
  saturation: 0.8572064769389753
  rhythmicContrast: 0.2615163666771559
  brandColors:
    - '#10222B'
    - '#95AB63'
    - '#BDD684'
    - '#E2F0D6'
    - '#F6FFE0'
github: true
layout_spectrum: 0.2677571942733767
analytics:
  google: UA-113319641-1
author:
  name: Mystic
  email: johnkelly.main@gmail.com
name: mysticstatistic
url: 'http://mysticstatistic.com'
navigation:
  - name: About Me
    id: 84a914e3-b9a2-44e2-88b8-19407ebe9cd7
    type: content
title: that mystic statistic...
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/2a7eef9e-4dd1-4d82-9d9d-3a9873bc9ff1.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/2a7eef9e-4dd1-4d82-9d9d-3a9873bc9ff1.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
coverPrefs:
  filter: false
description: some data dudes rambling
purpose:
  - type: contact
    url: 'mailto:johnkelly.main@gmail.com'
    label: Contact me
  - type: internal
    label: about me
    item: 84a914e3-b9a2-44e2-88b8-19407ebe9cd7
