layout_spectrum: 0.6187376189819251
typography_spectrum: 0.494194381847369
color:
  brandStrength: 0.18256750035551514
  lightness: 0.35982303118868036
  saturation: 0.8682992541599134
  rhythmicContrast: 0.1702842398826033
  brandColors:
    - '#000000'
    - '#333333'
    - '#FF358B'
    - '#01B0F0'
    - '#AEEE00'
coverPrefs:
  filter: false
github: true
author:
  name: Mystic
  email: johnkelly.main@gmail.com
name: mysticstatistic
title: that mystic statistic...
content: []
description: (but there's no sexy times.)
purpose:
  - type: contact
    url: 'mailto:johnkelly.main@gmail.com'
    label: Contact me
  - type: contact
    url: 'tel:07808014470'
    label: Call 07808014470
url: 'http://mysticstatistic.com'
